import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SupabaseProvider } from "@/providers/supabse.provider";
import AxiosProvider from "@/services/axios/axios.provider";
import { TanstackProvider } from "@/providers/tanstack.provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />

        <TanstackProvider>
          <SupabaseProvider>
            <AxiosProvider>{children}</AxiosProvider>
          </SupabaseProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
